config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help', as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]

  # About Shopping cart
  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'

  resources :products
  resources :orders
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 6)
      @current_user = current_user
    end
    fetch_products
  end

  def products; end

  def about; end

  def contact; end

  private

  def fetch_products
    @products = if params[:search]
                  Product.search(params[:search])
                         .order('created_at ASC')
                         .paginate(page: params[:page], per_page: 5)
                else
                  Product.order('created_at ASC')
                         .paginate(page: params[:page], per_page: 5)
                end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,("About")) %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title,("Contact")) %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,("Help")) %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title,("Home")) %>
  <div class="container">
    <div class="row">
      <!-- Carousel -->
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag("carousel1.jpg", :alt => "rss feed" , class: "img2") %>
            <!-- <img class="img2" src="/images/carousel1." alt="First slide"> -->
            <!-- Static Header -->
            <div class="header-text hidden-xs">
              <div class="col-md-12 text-center">
                <h2 style="color:white">
                  <span><%= link_to image_tag("logo.png",size:"64x64" , alt: "Shop logo"), 'http://rubyonrails.org/' %>
                    Welcome to
                    <strong>Dope Shop</strong>
                  </span>
                </h2>
                <br>

                <br>
                <!-- <div class=""> <a class="btn btn-theme btn-sm btn-min-block" href="#">Login</a> <a class="btn btn-theme btn-sm btn-min-block" href="#">Register</a> </div> -->
              </div>
            </div>
            <!-- /header-text -->
          </div>
          <div class="item">
            <%= image_tag("carousel2.jpg", :alt => "rss feed" , class: "img2") %>
            <!-- <img class="img2" src="http://unsplash.s3.amazonaws.com/batch%209/barcelona-boardwalk.jpg" alt="Second slide"> -->
            <!-- Static Header -->
            <div class="header-text hidden-xs">
              <div class="col-md-12 text-center">
                <h2 style="color:white">
                  <span>Best products on best prices!</span>
                </h2>
                <br>
                <br>
                <!-- <div class=""> <a class="btn btn-theme btn-sm btn-min-block" href="#">Login</a> <a class="btn btn-theme btn-sm btn-min-block" href="#">Register</a> </div> -->
              </div>
            </div>
            <!-- /header-text -->
          </div>
          <div class="item">
            <%= image_tag("carousel3.jpg", :alt => "rss feed" , class: "img2") %>
            <!-- <img class="img2" src="http://unsplash.s3.amazonaws.com/batch%209/barcelona-boardwalk.jpg" alt="Third slide"> -->
            <!-- Static Header -->
            <div class="header-text hidden-xs">
              <div class="col-md-12 text-center">
                <h2 style="color:white">
                  <span>Start exploring</span>
                </h2>
                <br>
                <br>
                <!-- <div class=""> <a class="btn btn-theme btn-sm btn-min-block" href="#">Login</a> <a class="btn btn-theme btn-sm btn-min-block" href="#">Register</a> </div> -->
              </div>
            </div>
            <!-- /header-text -->
          </div>
        </div>
        <!-- Controls -->
        <!-- <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span> </a> <a class="right carousel-control" href="#carousel-example-generic" data-slide="next"> <span
        class="glyphicon glyphicon-chevron-right"></span> </a> -->
      </div>
      <!-- /carousel -->
    </div>
  </div>
  <% if false %>
    <% if logged_in? %>
      <div class="row">
        <aside class="col-md-4">
          <section class="user_info">
            <%= render 'shared/user_info' %>
          </section>
          <section class="micropost_form">
            <%= render 'shared/micropost_form' %>
          </section>
        </aside>
        <div class="col-md-8">
          <h3>Micropost Feed</h3>
          <%= render 'shared/feed' %>
        </div>
      </div>
    <%end %>
    <%# else %><% end %>
    <% if !logged_in? %>
      <div class="center jumbotron">
        <!-- <h2> <%#= link_to image_tag("logo.png",size:"64x64" , alt: "Shop logo"), 'http://rubyonrails.org/' %> Welcome to dopeshop! </h2> -->

        <% if !logged_in? %>
          <%= link_to "Log in", login_path, class: "btn btn-lg btn-success" %>
          <strong >
            or
          </strong>
          <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
        <% end %>
      </div>
    <%end %>

    <%= render 'shared/products' %>
    <%# end %>