config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help', as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]

  # About Shopping cart
  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'

  resources :products
  resources :orders
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_cart.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Cart</h1>
  </div>
</section>

<div class="container mb-4">
  <div class="row">
    <div class="col-12">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Product</th>
              <th scope="col">Available</th>
              <th scope="col" class="text-center">Quantity</th>
              <th scope="col" class="text-right">Price</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @cart.line_items.each do |line_item| %>
              <%= render 'shared/cart_line_item' , :product => line_item.product , :line_item => line_item %>
            <% end %>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Sub-Total</td>
              <td class="text-right"><%= number_to_currency(@cart.sub_total) %></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>Shipping</td>
              <td class="text-right">free</td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>
                <strong>Total</strong>
              </td>
              <td class="text-right">
                <strong><%= number_to_currency(@cart.sub_total) %></strong>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col mb-2">
      <div class="row">
        <div class="col-sm-12  col-md-4">
          <%= button_to "Continue Shopping", root_path , class: "btn btn-block btn-light" , method: :get%>
        </div>
        <% if(@current_cart.line_items.count !=0 ) %>
          <div class="col-sm-12  col-md-4">
            <%= button_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-lg btn-block btn-warning text-uppercase"%>
          </div>
          <div class="col-sm-12 col-md-4 text-right">
            <%= button_to "Checkout", new_order_path , method: :get,class: "btn btn-lg btn-block btn-success text-uppercase"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_cart2.html.erb
<div class="center jumbotron">
  <p>
    <h3>Total price:
      <%= number_to_currency(@cart.sub_total) %></h3>
  </p>
  <ul class="users">
    <% @cart.line_items.each do |line_item| %>
      <%= render 'shared/product' , :product => line_item.product %>
      <li>Quantity:
        <%= line_item.quantity %>
        | Total Price:
        <%= number_to_currency(line_item.total_price) %>
        <!-- See lineItem section below for explanation of line_item links -->

        <hr class="style18">
      <% end %>
  </ul>

</div>

app/views/shared/_cart_line_item.html.erb
<tr>
  <td><%= link_to product do%>
    <% if product.picture? %>
      <%= image_tag product.picture.url , size:"90x90"%>
    <% else %>
      <%= image_tag "no_image.png", size:"90x90" %>
    <%end%>
  <%end %>
  x
  <%= line_item.quantity %>
</td>
<td><%= product.name %></td>
<td>In stock</td>
<td class="text-center">
  <!-- reduce -->
  <%=link_to line_item_reduce_path(:id => line_item) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
  <i class="glyphicon glyphicon-minus" style="color:white;"></i>

<% end %>
<!-- add -->
<%=link_to line_item_add_path(:id => line_item) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
<i class="glyphicon glyphicon-plus" style="color:white;"></i>
<% end %>
</td>
<td class="text-right"><%= product.price %>
$</td>
<td class="text-right">
<!-- Remove -->
<%=link_to line_item_path(line_item) ,method: :delete ,class: "btn btn-danger", data: { confirm: 'Are you sure?' } do %>
<i class="fa fa-trash"></i>
<% end %>
</td>
</tr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <%= will_paginate @feed_items %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "Compose new micropost..." %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<%# if (Rails.env.development? || Rails.env.test?) %>
<span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
<%# end %>
<% end %>

<script type="text/javascript">
$('#micropost_picture').bind('change', function () {
  var size_in_megabytes = this.files[0].size / 1024 / 1024;
  if (size_in_megabytes > 5) {
    alert('Maximum file size is 5MB. Please choose a smaller file.');
  }
});
</script>

app/views/shared/_order_product.html.erb
<li>

  <%= link_to product do%>
  <% if product.picture? %>
    <%= image_tag product.picture.url , size:"64x64" %>
  <% else %>
    <%= image_tag "no_image.png", size:"64x64" %>
  <%end%>
<%end %>

<strong>
  Name :
</strong>
<%= product.name %>
,<strong>
  Description :
</strong>
<%= product.description %>
<strong>
  Price :
</strong>
<%= product.price %> $

</li>

app/views/shared/_product.html.erb
<li>

  <%= link_to product do%>
  <% if product.picture? %>
    <%= image_tag product.picture.url , size:"100x100"%>
  <% else %>
    <%= image_tag "no_image.png", size:"100x100" %>
  <%end%>
<%end %>

<strong>
  Name :
</strong>
<%= product.name %>
,<strong>
  Description :
</strong>
<%= product.description %>
<strong>
  Price :
</strong>
<%= product.price %> $


<p>

<!-- Only Admin is allowed to modify products -->
<% if logged_in? && current_user.admin? %>
  <%= link_to 'Edit', edit_product_path(product) %>
  or
  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</p>
</li>

app/views/shared/_products.html.erb
<!-- <input type="text" class="form-control" placeholder="Search...."/> <div class="input-group-btn"> <div class="btn-group" role="group"> <div class="dropdown dropdown-lg"> -->
<!-- <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> <span class="caret"></span></button> <div class="dropdown-menu dropdown-menu-right" role="menu"> <form class="form-horizontal"
role="form"> <div class="form-group"> <label for="filter">Filter by</label> <select class="form-control"> <option value="0">Featured</option> <option value="1">Most popular</option> <option value="2" selected="selected">Top rated</option> <option
value="3">Most commented</option> </select> </div> <div class="form-group"> <label for="contain">Top Seller</label> <input class="form-control" type="text"/> </div> <div class="form-group"> <label for="contain">Contains the words</label> <input
class="form-control" type="text"/> </div> <button type="submit" class="btn btn-primary"> <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button> </form> </div> -->
<!-- </div> <button type="button" class="btn btn-primary"> <span class="glyphicon glyphicon-search" aria-hidden="true"></span></button> </div> </div> -->

<div class="center jumbotron">
  <h2>
    <% if params[:search].blank?  %>
      All Products (<%= @products.count %>)
    <%else %>
      Found => [
      <%= pluralize(@products.count, " ] Product") %>
    <%end %>
  </h2>

<!-- Search Bar -->
<%= form_tag(root_url, :method => "get", id: "search-form") do %>
<div class="input-group" id="adv-search">
  <%= text_field_tag :search, params[:search], placeholder: "Search..." , class: "form-control" %>
  <div class="input-group-btn">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    <span class="glyphicon glyphicon-search"></span>
  <% end %>
  </div>
</div>
<% end %>

<!-- Only Admin is allowed to create new products -->
<% if logged_in? && current_user.admin? %>
<%= link_to new_product_path , class: "btn btn-success" , style: "margin-top:15px;" do %>
<i class="glyphicon glyphicon-plus" style="color:black;"></i>
Create New Product (Admin)
<%end %>
<% end %>
</div>


<%= will_paginate @products %>

<ul class="users">
<% if @products.present? %>

<%= render @products %>
<%# @products.each do |product| %>
<%#= render 'shared/product' , product: product %>
  <%# end %>
  </ul>

  <%= will_paginate @products %>

<% else %>
  <p>
    <br/><br/><hr/>
    There are no products containing the term(s) => [
    <strong><%= params[:search] %></strong>
    ] .

  </p>
<% end %>
<br>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<% if current_user.admin? %>
  <span>
    <strong>Administrator</strong>
  </span>
<%end%>
<% if current_user.admin? && !current_user?(user) %>
  |
  <%= link_to "delete", user, method: :delete, data: { confirm: "Sure you want to delete user [ #{user.name} ]" } %>
<% end %>