config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help', as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]

  # About Shopping cart
  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'

  resources :products
  resources :orders
  resources :relationships,       only: [:create, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :picture, ProductPictureUploader
  has_many :line_items, dependent: :destroy
  has_many :orders, through: :line_items

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action  :set_product, only: %i[show edit update destroy]
  before_action  :user_is_admin, only: %i[create edit update destroy]

  # GET /products
  # GET /products.json
  def index
    # @products = Product.all.paginate(page: params[:page], per_page: 5)
    # @current_user = current_user
    redirect_to root_url
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        product_save_success_response(format,
                                      'Product was successfully created.')
      else
        product_save_failure_response(format, :new)
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        product_save_success_response(format,
                                      'Product was successfully updated.')
      else
        product_save_failure_response(format, :edit)
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
      flash[:info] = 'Product was successfully destroyed.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def product_save_success_response(format, message)
    format.html { redirect_to @product }
    format.json { render :show, status: :created, location: @product }
    flash[:info] = message
  end

  def product_save_failure_response(format, action)
    format.html { render action }
    format.json do
      render json: @product.errors,
             status: :unprocessable_entity
    end
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :picture, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
<div class="form-group">
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %>
        prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price, class: "form-control" %>
  </div>

  <div class="picture">
    <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/products/_product.html.erb
<li>

  <%= link_to product do%>
  <% if product.picture? %>
    <%= image_tag product.picture.url %>
  <% else %>
    <%= image_tag "no_image.png", size:"150x150" %>
  <%end%>
<%end %>

<strong>
  Name2 :
</strong>
<%= product.name %>
,<strong>
  Description :
</strong>
<%= product.description %>
<strong>
  Price :
</strong>
<%= product.price %>
$

<p>

  <%if !@current_cart.products.include?(product)%>
    <%# if logged_in? %>
      <!-- Add to Basket -->
      <%=button_to line_items_path(:product_id => product.id), class: "btn btn-warning" , style: "margin-top:15px;" , params:{productID: product.id} do %>
      <i class="glyphicon glyphicon-plus" style="color:black;"></i>
      Add to Basket
    <% end %>
    <%# end %>
    <%else %>
      <!-- See lineItem section below for explanation of line_item links -->

      <!-- <li> -->
      <!-- <%#= link_to "Add one", line_item_add_path(:id => line_item), method: :post %> -->

      <!-- reduce -->
      <%=link_to line_item_reduce_path(:id =>@current_cart.line_items.find_by(product_id: product.id)) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
      <i class="glyphicon glyphicon-minus" style="color:black;"></i>
      Reduce
    <% end %>

    <!-- add -->
    <%=link_to line_item_add_path(:id => @current_cart.line_items.find_by(product_id: product.id)) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
    <i class="glyphicon glyphicon-plus" style="color:black;"></i>
    Add
  <% end %>

  <!-- Remove -->
  <%=link_to line_item_path(@current_cart.line_items.find_by(product_id: product.id)) ,method: :delete ,class: "btn btn-warning" , style: "margin-top:15px;" do %>
  <i class="glyphicon glyphicon-remove" style="color:black;"></i>
  Remove Item
<% end %>

<li>
  Quantity:
  <%= @current_cart.line_items.find_by(product_id: product.id).quantity %>
  | Total Price:
  <%= number_to_currency(@current_cart.line_items.find_by(product_id: product.id).total_price) %>

</li>
<%end %>
</p>

<p>

<!-- Only Admin is allowed to modify products -->
<% if logged_in? && current_user.admin? %>
<%= link_to edit_product_path(product) do %>
<i class="glyphicon glyphicon-pencil" style="color:darkgray"></i>
Edit
<% end %>
or
<!-- Basket -->
<%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
<i class="glyphicon glyphicon-fire" style="color:firebrick"></i>
Destroy
<% end %>
<% end %>
</p>
</li>

app/views/products/_product_image.html.erb
<% if product.picture? %>
  <%= image_tag product.picture.url %>
<% else %>
  <%= image_tag "no_image.png", size:"150x150" %>
<%end%>

app/views/products/_product_show.html.erb
<div class="container">
  <div class="card">
    <div class="container">
      <div class="wrapper row">
        <div class="preview col-md-6">

          <div class="preview-pic tab-content">
            <div class="tab-pane active" id="pic-1">
              <%= render 'product_image' , :product => @product%>
            </div>
            <div class="tab-pane" id="pic-2">
              <%= render 'product_image' , :product => @product%>
            </div>
            <div class="tab-pane" id="pic-3">
              <%= render 'product_image' , :product => @product%>
            </div>
          </div>
          <ul class="preview-thumbnail nav nav-tabs">
            <li class="active">
              <a data-target="#pic-1" data-toggle="tab"><%= render 'product_image' , :product => @product%></a>
            </li>
            <li>
              <a data-target="#pic-2" data-toggle="tab"><%= render 'product_image' , :product => @product%></a>
            </li>
            <li>
              <a data-target="#pic-3" data-toggle="tab"><%= render 'product_image' , :product => @product%></a>
            </li>
          </ul>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @product.name %></h3>
          <div class="rating">
            <div class="stars">
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
            </div>
            <span class="review-no">41 reviews</span>
          </div>
          <p class="product-description"><%= @product.description %></p>
          <h4 class="price">current price:
            <span>$<%= @product.price %></span></h4>
          <p class="vote">
            <strong>91%</strong>
            of buyers enjoyed this product!
            <strong>(87 votes)</strong>
          </p>
          <h5 class="sizes">sizes:
            <span class="size" data-toggle="tooltip" title="small">s</span>
            <span class="size" data-toggle="tooltip" title="medium">m</span>
            <span class="size" data-toggle="tooltip" title="large">l</span>
            <span class="size" data-toggle="tooltip" title="xtra large">xl</span>
          </h5>
          <h5 class="colors">colors:
            <span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
            <span class="color green"></span>
            <span class="color blue"></span>
          </h5>
          <div class="action">

            <%if !@current_cart.products.include?(product)%>
              <%# if logged_in? %>
                <!-- Add to Basket -->
                <%=button_to line_items_path(:product_id => product.id), class: "btn btn-warning" , style: "margin-top:15px;" , params:{productID: product.id} do %>
                <i class="glyphicon glyphicon-plus" style="color:black;"></i>
                Add to Basket
              <% end %>
              <%# end %>
              <%else %>

                <!-- See lineItem section below for explanation of line_item links -->
                <ul class="users">
                  <!-- <li> -->
                  <!-- <%#= link_to "Add one", line_item_add_path(:id => line_item), method: :post %> -->

                  <!-- reduce -->
                  <%=link_to line_item_reduce_path(:id =>@current_cart.line_items.find_by(product_id: product.id)) , method: :post, class: "btn btn-danger" , style: "margin-top:15px;" do %>
                  <i class="glyphicon glyphicon-minus" style="color:black;"></i>
                  Reduce
                <% end %>

                <!-- add -->
                <%=link_to line_item_add_path(:id => @current_cart.line_items.find_by(product_id: product.id)) , method: :post , class: "btn btn-success" , style: "margin-top:15px;" do %>
                <i class="glyphicon glyphicon-plus" style="color:black;"></i>
                Add
              <% end %>

              <!-- Remove -->
              <%=link_to line_item_path(@current_cart.line_items.find_by(product_id: product.id)) ,method: :delete ,class: "btn btn-warning" , style: "margin-top:15px;" do %>
              <i class="glyphicon glyphicon-remove" style="color:black;"></i>
              Remove Item
            <% end %>

            <li>Quantity:
              <%= @current_cart.line_items.find_by(product_id: product.id).quantity %>
              | Total Price:
              <%= number_to_currency(@current_cart.line_items.find_by(product_id: product.id).total_price) %>
              <hr class="style18"/>
          </ul>
        <%end %>
      </p>

      <p>

        <!-- Only Admin is allowed to modify products -->
        <% if logged_in? && current_user.admin? %>
          <%= link_to edit_product_path(product) do %>
          <i class="glyphicon glyphicon-pencil" style="color:darkgray"></i>
          Edit
        <% end %>
        or
        <!-- Basket -->
        <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-fire" style="color:firebrick"></i>
        Destroy
      <% end %>
    <% end %>
  </p>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title,("Products")) %>

  <p id="notice"><%= notice %></p>

  <div class="center jumbotron">

      <strong>Products ( <%= @products.count %> )</strong>

  </div>

  <%= render 'shared/products' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center jumbotron">
  <ul class="users">
    <%= render 'products/product_show' , :product => @product%>
  </ul>
</div>