config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help', as: 'helf'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]

  # About Shopping cart
  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items' => 'line_items#create'
  get 'line_items/:id' => 'line_items#show', as: 'line_item'
  delete 'line_items/:id' => 'line_items#destroy'

  resources :products
  resources :orders
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<nav class="navbar  navbar-inverse">
  <div class="container-fluid">
    <!-- FOOTER START================== -->
    <footer class="footer">
      <div class="container">

        <%= render "/layouts/reviews" %>

        <hr class="style15">

        <div class="row">
          <div class="col-sm-3">
            <h4 class="title">About us</h4>
            <p>With 5 years market experience we are here to give you the best products on the best price .</p>
            <!-- <ul class="social-icon"> <a href="#" class="social"><i class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#" class="social"><i class="fa fa-twitter" aria-hidden="true"></i></a> <a href="#" class="social"><i class="fa fa-instagram"
            aria-hidden="true"></i></a> <a href="#" class="social"><i class="fa fa-youtube-play" aria-hidden="true"></i></a> <a href="#" class="social"><i class="fa fa-google" aria-hidden="true"></i></a> <a href="#" class="social"><i class="fa fa-dribbble"
            aria-hidden="true"></i></a> </ul> -->
          </div>
          <div class="col-sm-3">
            <h4 class="title">My Account</h4>
            <span class="acount-icon">
              <%= link_to orders_path do %>
              <i class="fa fa-heart" aria-hidden="true"></i>
              Orders
            <% end %>
            <%= link_to cart_path(@current_cart) do %>
            <i class="fa fa-cart-plus" aria-hidden="true"></i>
            Cart
          <% end %>
          <%= link_to current_user do %>
          <i class="fa fa-user" aria-hidden="true"></i>
          Profile
        <% end %>
        <%= link_to users_path do %>
        <i class="fa fa-users" aria-hidden="true"></i>
        Users
      <% end %>
      <!-- <a href="#"> <i class="fa fa-globe" aria-hidden="true"></i> Language</a> -->
    </span>
  </div>
  <div class="col-sm-3">
    <h4 class="title">Category</h4>
    <div class="category">
      <a href="#">Men</a>
      <a href="#">Women</a>
      <a href="#">Boy</a>
      <a href="#">Girl</a>
      <a href="#">Bag</a>
      <a href="#">Toys</a>
      <a href="#">Hair Accessories</a>
      <a href="#">Shoes</a>
      <a href="#">Glasses</a>
      <a href="#">Baby clothes</a>
    </div>
  </div>
  <div class="col-sm-3">
    <h4 class="title">Payment Methods</h4>
    <p>You can pay using...</p>
    <ul class="payment">
      <li>
        <a href="#">
          <i class="fa fa-cc-amex" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-credit-card" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-paypal" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-cc-visa" aria-hidden="true"></i>
        </a>
      </li>
    </ul>
  </div>
</div>
<hr class="style18">

<div class="row text-center">
  ©
  <%= Date.today.year %>
  .
  <a href="http://www.goxr3plus.co.nf" target="_blank">GOXR3PLUS Studio
  </a>
</div>
</div>

</footer>

</div>
</div>

</div>
</nav>

app/views/layouts/_header.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="nav-btn btn-dark btn-lg accordion-toggle pull-left collapsed" title="Follow Us" role="tab" id="social-collapse" data-toggle="collapse" data-parent="#accordion" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne"></a>
      <!-- <a id="menu-toggle" href="#" class="nav-btn btn-dark btn-lg toggle"> <i class="fa fa-bars" style="color:#fff;"></i> </a> -->
      <a id="to-top" class="btn btn-lg btn-inverse" href="#top">
        <span class="sr-only">Toggle to Top Navigation</span>
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse js-navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <a class="navbar-brand" href="#">
          <%= link_to "Dope Shop", root_path, id: "logo" %>
          <%= link_to image_tag("logo.png",size:"52x52" , alt: "Rails logo"), root_path %>
        </a>    
        <!-- <li> <a href="#">Store locator</a> </li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- Home -->
        <li><%= link_to root_path do %>
          <i class="glyphicon glyphicon-home"></i>
          Home
        <% end %>
      </li>

      <!-- Users -->
      <% if logged_in? %>

        <li><%= link_to users_path do %>
          <i class="fa fa-users"></i>
          Users
          <span class="badge ">
            <i id="total_cart_items_badge">(<%= User.count %>)</i>
          </span>
        <% end %>
      </li>

      <!-- Cart -->
      <li><%= link_to cart_path(@current_cart) do %>
        My Cart
        <span class="badge ">
          <i class="fa fa-cart-plus" style="color:#FFD700; font-size:20px"></i>

          <i id="total_cart_items_badge">(<%= @current_cart.line_items.count %>)</i>
        </span>
      <% end %>
    </li>

    <!-- Orders -->
    <li><%= link_to orders_path do %>
      My Orders
      <span class="badge ">
          <i class="fa fa-shopping-basket" style="color:#FFD700; font-size:20px"></i>
        <%if @current_user.admin? %>
          (<%= @current_user.orders.count %>) Admin / (<%= Order.count%>) Total
        <% else %>
          <%= @current_user.orders.count %>
        <% end %>

      </span>
    <% end %>
  </li>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= gravatar_for @current_user, size: 20 %>
      Account
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <div class="navbar-content">
          <div class="row">
            <div class="col-md-5">
              <!-- <img src="http://placehold.it/120x120" alt="Alternate Text" class="img-responsive"/> -->
              <%= gravatar_for @current_user, size: 120 %>
              <p class="text-center small">
                <%= link_to edit_user_path(current_user) do %>
                <i class="glyphicon glyphicon-picture"></i>
                Change Photo
              <% end %>
            </p>
          </div>
          <div class="col-md-7">
            <span><%= @current_user.name %></span>
            <p class="text-muted small">
              <%= @current_user.email %></p>
            <div class="divider"></div>
            <%= link_to current_user , class: "btn btn-primary btn-sm active" do %>
            <i class="glyphicon glyphicon-eye-open"></i>
            View Profile
          <% end %>
        </div>
      </div>
    </div>
    <div class="navbar-footer">
      <div class="navbar-footer-content">
        <div class="row">
          <div class="col-md-6">
            <%= link_to edit_user_path(current_user), class:"btn btn-default btn-sm" do %>
            <i class="glyphicon glyphicon-cog"></i>
            Change Password
          <% end %>
        </div>
        <div class="col-md-6">
          <%= link_to logout_path,class: "btn btn-default btn-sm pull-right", method: :delete do %>
          <i class="glyphicon glyphicon-off"></i>
          Sign out
        <% end %>
      </div>
    </div>
  </div>
</div>
</li>
</ul>
</li>

<% else %>

<!-- Log In -->
<li><%= link_to login_path do %>
<i class="glyphicon glyphicon-log-out"></i>
Log In
<% end %>
</li>

<% end %>
</ul>
</ul></div><!-- /.nav-collapse --> </div> <!-- /.container-fluid --></nav><aside id="accordion" class="social text-vertical-center"> <div class="accordion-social"><ul class="panel-collapse nav nav-stacked collapse" role="tabpanel" aria-labelledby="social-collapse" id="collapseOne" aria-expanded="false">
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-facebook"></i>
</a>
</li>
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-twitter"></i>
</a>
</li>
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-google-plus"></i>
</a>
</li>
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-github"></i>
</a>
</li>
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-linkedin"></i>
</a>
</li>
<li>
<!-- <a href="skype:live:soldierupdesigns?call"> <i class="fa fa-lg fa-skype" target="_blank"></i> </a> -->
</li>
<li>
<a href="http://www.goxr3plus.co.nf" target="_blank">
<i class="fa fa-lg fa-stack-exchange"></i>
</a>
</li></ul> </div></aside>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= favicon_link_tag asset_path('logo.png'), :rel => 'icon', :type => 'image/png' %>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>

    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield :header %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>

      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>

    <!-- <script type="text/javascript">
      $(function () {
        alert("hi");
      });
    </script> -->

  </body>
</html>